import type { TermsSection } from './termsAndConditions';

export const PRIVACY_LAST_UPDATED = '16 September 2026';
export const PRIVACY_SECTIONS: TermsSection[] = [
  { heading: '1. Controller / Pengawal data', body: ['JomDekan operates the platform and determines how personal data is processed. Before public launch, the operator must insert its full legal identity, registration details, service address, and monitored privacy contact here.', 'JomDekan mengendalikan platform dan menentukan cara data diproses. Sebelum pelancaran awam, pengendali mesti memasukkan identiti undang-undang, butiran pendaftaran, alamat penyampaian dan hubungan privasi yang dipantau.'] },
  { heading: '2. Data collected / Data dikumpulkan', body: ['We collect account/profile and university details; authentication and security records; resources and files; discussions, comments and votes; favourites; tutor and opportunity listings or applications; reports and evidence; support requests; notifications; AI inputs, outputs and usage; and technical request, IP, audit and error information.', 'Kami mengumpulkan butiran akaun/profil dan universiti; rekod keselamatan; sumber dan fail; aktiviti komuniti; kegemaran; penyenaraian atau permohonan; laporan; sokongan; pemberitahuan; input, output dan penggunaan AI; serta maklumat teknikal, IP, audit dan ralat.'] },
  { heading: '3. Purposes / Tujuan', body: ['We use data to create and secure accounts; provide JomDekan features; generate requested AI functions; communicate about the service; prevent abuse; moderate content; troubleshoot; maintain audit records; and understand service performance. Mandatory registration is not consent to marketing.', 'Data digunakan untuk menyediakan dan melindungi JomDekan, menjana ciri AI yang diminta, komunikasi operasi, pencegahan penyalahgunaan, penyederhanaan, penyelesaian masalah, audit dan prestasi. Pendaftaran wajib bukan persetujuan pemasaran.'] },
  { heading: '4. AI processing / Pemprosesan AI', body: ['Requested AI features may send relevant extracted resource text and your question from the backend to the configured AI provider. JomDekan does not intentionally send passwords, access tokens, uploader email, or unrelated profile details. Do not include unnecessary confidential or personal data.', 'Ciri AI yang diminta mungkin menghantar teks sumber berkaitan dan soalan anda kepada penyedia AI. Kata laluan, token akses, e-mel pemuat naik atau profil yang tidak berkaitan tidak dihantar dengan sengaja.'] },
  { heading: '5. Disclosure and overseas processing / Pendedahan dan pemprosesan luar negara', body: ['Service providers may process data for hosting, databases, file storage, email, AI, security, and diagnostics, including outside Malaysia. Before launch, the operator must identify production providers and destinations and confirm appropriate contractual and cross-border safeguards. Disclosure may also occur where required by law or necessary to protect users.', 'Penyedia perkhidmatan mungkin memproses data untuk pengehosan, pangkalan data, storan, e-mel, AI, keselamatan dan diagnostik, termasuk di luar Malaysia. Penyedia, destinasi dan perlindungan produksi mesti dikenal pasti sebelum pelancaran.'] },
  { heading: '6. Cookies and browser storage / Kuki dan storan pelayar', body: ['JomDekan uses an HTTP-only refresh cookie for authentication and local storage for the selected visual theme. Access tokens are held in memory. Analytics or non-essential cookies must not be added without first updating this notice and any required consent control.', 'JomDekan menggunakan kuki refresh HTTP-only untuk pengesahan dan storan setempat untuk tema. Token akses disimpan dalam memori. Kuki analitik atau tidak penting memerlukan notis dan kawalan persetujuan yang dikemas kini.'] },
  { heading: '7. Retention / Penyimpanan', body: ['Data is retained only as needed for the stated purposes, account operation, security, moderation, disputes, backups, and legal duties. The repository does not define a complete production retention schedule; the operator must approve and publish specific periods before launch.', 'Data disimpan hanya selama diperlukan. Jadual penyimpanan produksi khusus mesti diluluskan dan diterbitkan sebelum pelancaran.'] },
  { heading: '8. Security and incidents / Keselamatan dan insiden', body: ['Controls include hashed passwords, access control, validation, parameterised queries, protected refresh cookies, file checks, rate limits, and audit logging. No system is completely secure. The operator must maintain incident response and make legally required breach notifications.', 'Kawalan termasuk kata laluan bercincang, kawalan akses, pengesahan, pertanyaan berparameter, kuki terlindung, semakan fail, had kadar dan log audit. Pengendali mesti mengekalkan tindak balas insiden dan pemberitahuan diwajibkan undang-undang.'] },
  { heading: '9. Rights and choices / Hak dan pilihan', body: ['Subject to law, you may request information, access, correction, withdrawal of consent where applicable, objection to direct marketing, or deletion where retention is no longer required. Submit requests through Help & Support; identity verification may be required. You may also contact Malaysia’s Personal Data Protection Commissioner.', 'Tertakluk kepada undang-undang, anda boleh meminta maklumat, akses, pembetulan, penarikan persetujuan, bantahan pemasaran langsung atau pemadaman. Hantar melalui Bantuan & Sokongan; pengesahan identiti mungkin diperlukan.'] },
  { heading: '10. Changes and contact / Perubahan dan hubungan', body: ['Material changes should be communicated through JomDekan. Use Help & Support for privacy requests. Before launch, add a direct privacy email and postal/service address.', 'Perubahan penting hendaklah dimaklumkan melalui JomDekan. Gunakan Bantuan & Sokongan untuk permintaan privasi. E-mel privasi dan alamat mesti ditambah sebelum pelancaran.'] },
];
