export interface TermsSection { heading: string; body: string[] }

export const TERMS_LAST_UPDATED = "16 September 2026";

export const TERMS_SECTIONS: TermsSection[] = [
  { heading: "1. Agreement and eligibility", body: ['These Terms & Conditions ("Terms") govern your use of JomDekan. By creating an account or using the service, you agree to these Terms and acknowledge the separate Privacy Notice. If you do not agree, do not use JomDekan.', "You must provide accurate information and use the service only for lawful academic, community, tutoring, and opportunity-related purposes. If you cannot enter this agreement independently because of your age, use JomDekan only with permission from a parent or legal guardian."] },
  { heading: "2. Accounts and security", body: ["You are responsible for safeguarding your password and activity through your account. Do not share passwords, tokens, or reset links. Notify JomDekan through Help & Support if you suspect unauthorised access.", "JomDekan may require email verification, expire or revoke sessions, and temporarily lock login attempts to protect accounts and the service."] },
  { heading: "3. Academic resources and uploads", body: ["Users may create text resources and upload one or more supported files. User-provided materials are not guaranteed to be accurate, complete, current, safe, authorised by a university, or free of third-party rights.", "You retain ownership of content you submit and grant JomDekan a non-exclusive, worldwide, royalty-free licence to store, process, reproduce, display, and distribute it only as needed to operate, secure, moderate, and improve the service. This ends when content is deleted except for lawful backups, audit records, and required retention.", "You confirm that you own the content or have permission to share it. Do not upload confidential examinations, leaked assessments, personal data belonging to others, malware, or material that infringes copyright or institutional rules."] },
  { heading: "4. AI summaries and resource assistant", body: ["When requested, JomDekan may send relevant extracted resource text and the user's question from its backend to the configured AI provider. Do not place secrets or unnecessary personal information in resources or AI questions.", "AI output is a study aid, not an authoritative source. It may be wrong, incomplete, or misleading. Verify important information against the original resource and do not treat output as professional, legal, medical, financial, or academic-authority advice.", "AI features do not edit original resources or make moderation, approval, grading, or administrative decisions."] },
  { heading: "5. Community conduct and academic integrity", body: ["Do not harass, threaten, impersonate, discriminate, spam, scam, manipulate votes, or post unlawful, defamatory, hateful, sexually explicit, violent, or privacy-invasive content.", 'JomDekan supports learning, mentoring, proofreading, and legitimate guidance. It must not be used to obtain answers during a live examination, impersonate a student, or commission or complete graded work for another person ("contract cheating"). You remain responsible for your institution\'s rules.'] },
  { heading: "6. Tutoring and freelance opportunities", body: ["JomDekan provides listings and communication pathways but is not the employer, tutor, student, client, payment processor, or contracting party in arrangements between users. Users must assess identity, suitability, scope, pricing, payment, tax, safety, and deliverables.", "A listing, profile, moderation status, or verification indicator is not a guarantee of identity, qualifications, quality, payment, conduct, or outcome."] },
  { heading: "7. Reports and moderation", body: ["Reports may include contact details, explanations, and optional evidence and are reviewed by authorised administrators. JomDekan may restrict, remove, or preserve content; issue warnings; suspend or delete accounts; notify affected users; and refer serious suspected unlawful activity to relevant authorities.", "Moderation may be imperfect, and submitting a report does not guarantee a particular outcome."] },
  { heading: "8. Intellectual property and takedowns", body: ["JomDekan's software, branding, and original interface materials remain protected by applicable law. These Terms do not transfer ownership to users.", "To report alleged infringement, use Help & Support and identify the work, disputed content and location, your contact details, and the basis of your claim. Knowingly false claims may have legal consequences."] },
  { heading: "9. Privacy and communications", body: ["JomDekan processes personal data as described in its Privacy Notice. Verification, password-reset, security, support, report-outcome, and moderation messages are operational communications.", "Registration does not provide consent to promotional email. If optional marketing is introduced, it must use a separate choice and withdrawal mechanism."] },
  { heading: "10. Availability and third-party services", body: ['JomDekan is provided on an "as available" basis. Features may be interrupted, changed, limited, or discontinued for maintenance, security, cost control, legal compliance, or technical reasons. File storage, email, hosting, databases, and AI may rely on third-party providers.'] },
  { heading: "11. Disclaimers and responsibility", body: ["To the extent permitted by Malaysian law, JomDekan does not guarantee user content, AI output, listings, uninterrupted availability, or a particular academic or commercial result. Nothing excludes rights or liabilities that cannot lawfully be excluded.", "You are responsible for losses or claims caused by your unlawful content, infringement, misuse, or material breach of these Terms, to the extent permitted by law."] },
  { heading: "12. Account and content termination", body: ["Self-service account deletion is not currently available. You may request assistance through Help & Support, and administrators may disable or delete accounts under applicable moderation and retention procedures.", "Termination does not remove obligations or rights that logically continue, including ownership, lawful record retention, disputes, and responsibility for earlier conduct."] },
  { heading: "13. Changes, law, and contact", body: ["JomDekan may update these Terms as the service or law changes. Material changes should be communicated and renewed acceptance obtained where required. These Terms are governed by Malaysian law, subject to mandatory rights and dispute processes.", "Use authenticated Help & Support for support, privacy, moderation, or takedown matters. Before public launch, the operator must add its legal name, registration details, service address, and monitored legal and privacy contacts here."] },
];
